image: Ubuntu1804
stack: node 14

cache: node_modules
before_build:
  - npm install webpack webpack-cli
  - npm install

build_script:
  - node_modules/.bin/webpack --config webpack.config.js

artifacts:
  - path: dist
    name: MyProject

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: main
