image: Ubuntu1804
stack: node 14

# cache:
#   node_modules: true

before_build:
  - npm install -g webpack webpack-cli
  - npm install

build_script:
  - npm run build

deploy:
  provider: Pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
